version: 2.1

orbs:
    win: sandbox/windows-tools@dev:preview

workflows:
    build:
        jobs:
            - build

jobs:
    build:
        executor: win/preview-default
        steps:
            - checkout
            - run:
                name: Check docker
                command: |
                    docker info
                    docker run mcr.microsoft.com/dotnet/framework/sdk:4.8
                    dotnet build --configuration Release
                    TestingFrameworkAppDocker\bin\Release\TestingFrameworkAppDocker.exe

