version: 2.1

orbs:
    win: sandbox/windows-tools@dev:preview

workflows:
    build:
        jobs:
            - build

jobs:
    build:
        docker:
            - image: mcr.microsoft.com/dotnet/framework/sdk:4.8
        steps:
            - checkout
            - run:
                name: Check docker
                command: |
                    docker info
                    dotnet build --configuration Release
                    TestingFrameworkAppDocker\bin\Release\TestingFrameworkAppDocker.exe

