version: 2.1

workflows:
    build:
        jobs:
            - build

jobs:
    build:
        machine:
            image: windows-server-2019
            resource_class: windows.medium
            shell: powershell.exe -NoProfile -ExecutionPolicy Bypass
        steps:
            - checkout
            - run:
                name: Build
                command: dotnet build --configuration Release
            - run:
                name: Run
                command: TestingFrameworkAppDocker\bin\Release\TestingFrameworkAppDocker.exe