version: 2.1

workflows:
    build:
        jobs:
            - build

jobs:
    build:
        docker:
            - image: mcr.microsoft.com/dotnet/framework/sdk:4.8-20190611-windowsservercore-ltsc2016
        steps:
            - checkout
            - run:
                name: Build
                command: dotnet build --configuration Release
            - run:
                name: Run
                command: TestingFrameworkAppDocker\bin\Release\TestingFrameworkAppDocker.exe